# Generated by Django 4.2.11 on 2024-04-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('authentication', 'Аутентификация'), ('transaction', 'Транзакция'), ('error', 'Ошибка')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
