# Generated by Django 4.2.11 on 2024-04-17 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_country', models.CharField(max_length=4)),
                ('merchant_city', models.CharField(default=None, max_length=128, null=True)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_currency', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.transactions', to_field='transaction_id')),
            ],
        ),
    ]
