# Generated by Django 4.2.11 on 2024-04-15 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=16)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_country', models.CharField(max_length=4)),
                ('merchant_city', models.CharField(default=None, max_length=128, null=True)),
                ('merchant_mcc', models.IntegerField()),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_currency', models.CharField(max_length=3)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_currency', models.CharField(max_length=3)),
                ('settlement_amount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('settlement_currency', models.CharField(default=None, max_length=3, null=True)),
                ('settled', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(blank=True, choices=[('CRT', 'Credit'), ('DBT', 'Debit')], max_length=3)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
