# Generated by Django 4.2.11 on 2024-04-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transfers_account_transfers_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='merchant_mcc',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='settled',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='settlement_amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='settlement_currency',
        ),
    ]
